### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Chrysanthemum536** [bbc/video-loop-finder#1]
INFO    Input loaded: video_duration=29422
INFO    Looping direction appears to be CW
CRITICAL        Failed to read frame 29420
Traceback (most recent call last):
  File "C:\video_loop_finder.py", line 665, in <module>
    start_frame_idx, end_frame_idx = vlf.find_closest_end_frame(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\video_loop_finder.py", line 269, in find_closest_end_frame
    raise RuntimeError(msg)
RuntimeError: Failed to read frame 29420

**Comment by alanhogan** [comment]
Interesting, I had the same error, also 2 frames before the expected final frame, although my video had only 750 frames (`video_duration`).

**Comment by alanhogan** [comment]
You may be able to bypass this error by changing lines 268-269 from

```py
logger.fatal(msg)
raise RuntimeError(msg)
```

to 

```py
logger.warning(msg)
```
