### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Maxhem2** [bbc/video-loop-finder#2]
INFO    Input loaded: video_duration=1222987
Traceback (most recent call last):
  File "D:\Win10Workstation\LoopKiller\video_loop_finder.py", line 654, in <module>
    vlf = VideoLoopFinder(
  File "D:\Win10Workstation\LoopKiller\video_loop_finder.py", line 158, in __init__
    self.flow_algo = cv2.optflow.createOptFlow_Farneback()
AttributeError: module 'cv2' has no attribute 'optflow'

**Comment by JanEickholt** [comment]
sorry for necrobumping, but for anyone with the same problem use `pip3 install opencv-contrib-python` instead of `opencv-python`

**Comment by alanhogan** [comment]
Thank you @JanEickholt, that resolved this issue for me! (Then I could move on to contend with #1)
